#ifndef TEXTURE_ATLAS_H
#define TEXTURE_ATLAS_H

#define TEXTURE_ATLAS_SIZE 64
#define TEXTURE_WALL_SOLID 1
#define TEXTURE_WALL_BREAKABLE 2
#define TEXTURE_PLAYER_FRONT 3
#define TEXTURE_PLAYER_LEFT 4
#define TEXTURE_PLAYER_RIGHT 5
#define TEXTURE_PLAYER_BACK 6

#endif