#ifndef TEXTURES_H
#define TEXTURES_H

#define TEXTURE_ATLAS_SIZE 64
#define TEXTURE_WALL_SOLID 1
#define TEXTURE_WALL_BREAKABLE 2
#define TEXTURE_PLAYER_FRONT 11
#define TEXTURE_PLAYER_LEFT 12
#define TEXTURE_PLAYER_RIGHT 13
#define TEXTURE_PLAYER_BACK 14
#define TEXTURE_BOMB 15
#define TEXTURE_EXPLOSION 16

#endif